name: docs.typo3.org Home Page

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'WebRootResources/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SCP files to production system
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_DOCS_HOST }}
          username: ${{ secrets.DEPLOY_DOCS_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "WebRootResources/*"
          rm: true
          strip_components: 1
          tar_tmp_path: ${{ secrets.TMP_TARGET_PATH }}
          target: ${{ secrets.TARGET_PATH }}
